### ISSUE TITLE
Swords using too much durability

### ISSUE THREAD

**Issue by daemitus** [LexManos/DwarfCraft#9]
So im currently 19 swordsman, got myself a durability tracker.

Typically on death, it only uses up 1 durability.

Quick testing, 

hit a spider twice, killed it, 2 durability each.
hit a skeleton twice, killed it, 1 durability each.
Killed 5 cows in one hit. 3 times, 2 durability. 2 times, 1 durability.

Since at 19, i have a .81 durability removed skill, best guess, is that the random function is doing a 1-2 instead of 0-1

**Comment by LexManos** [comment]
Minecraft does durability damage itself, this was never taken into account when the skill was implemented. 
Fixed in: https://github.com/LexManos/DwarfCraft/commit/8cffdcda95f3336a3fe61b254176c4e3fb40e899
Small issue with the fact that I have to actually HEAL the damage when the skill would negate it. Cause some artifacts when the sword is on the verge of breaking. But it works better now.
